// This file is generated by npm run build:icons

export type IconName =
  | "cross-2"
  | "font-bold"
  | "font-italic"
  | "heading"
  | "list-bullet"
  | "magnifying-glass"
  | "quote"
  | "strikethrough"
  | "underline";
